# Product Table Seed
Product.create(name: "Almond Toe Court Shoes", colour: "Patent Black", category: "Women’s Footwear", price: 99.00, stock: 5, :image => File.open('db/images/almond_toe_court_shoes.png', 'rb'))
Product.create(name: "Suede Shoes", colour: "Blue", category: "Women’s Footwear", price: 42.00, stock: 4, :image => File.open('db/images/suede_shoes.png', 'rb'))
Product.create(name: "Leather Driver Saddle Loafers", colour: "Tan", category: "Men’s Footwear", price: 34.00, stock: 12, :image => File.open('db/images/leather_driver_saddle_loafers.png', 'rb'))
Product.create(name: "Flip Flops", colour: "Red", category: "Men’s Footwear", price: 19.00, stock: 6, :image => File.open('db/images/flip_flops_red.png', 'rb'))
Product.create(name: "Flip Flops", colour: "Blue", category: "Men’s Footwear", price: 19.00, stock: 0, :image => File.open('db/images/flip_flops_blue.png', 'rb'))
Product.create(name: "Gold Button Cardigan", colour: "Black", category: "Women's Casualwear", price: 167.00, stock: 6, :image => File.open('db/images/gold_button_cardian.png', 'rb'))
Product.create(name: "Cotton Shorts", colour: "Medium Red", category: "Women's Casualwear", price: 167.00, stock: 6, :image => File.open('db/images/cotton_shorts_red.png', 'rb'))
Product.create(name: "Fine Stripe Short Sleeve Shirt", colour: "Grey", category: "Men's Casualwear", price: 49.99, stock: 9, :image => File.open('db/images/fine_stripe_grey_short_sleeve_shirt.png', 'rb'))
Product.create(name: "Fine Stripe Short Sleeve Shirt", colour: "Green", category: "Men's Casualwear", price: 49.99, stock: 3, :image => File.open('db/images/fine_stripe_green_short_sleeve_shirt.png', 'rb'))
Product.create(name: "Sharkskin Waistcoat", colour: "Charcoal", category: "Men's Formalwear", price: 75.00, stock: 2, :image => File.open('db/images/sharkskin_waistcoat.png', 'rb'))
Product.create(name: "Lightweight Patch Pocket Blazer", colour: "Deer", category: "Men's Formalwear", price: 175.50, stock: 1, :image => File.open('db/images/lightweight_patch_pocket_blazer.png', 'rb'))
Product.create(name: "Bird Print Dress", colour: "Black", category: "Women's Formalwear", price: 270.00, stock: 10, :image => File.open('db/images/bird_print_dress.png', 'rb'))
Product.create(name: "Mid Twist Cut-Out Dress", colour: "Pink", category: "Women's Formalwear", price: 540.00, stock: 5, :image => File.open('db/images/mid_twist_cut_out_dress.png', 'rb'))
